/**
 * @file
 * Describes the details of an event
 */

#ifndef EVENT_HPP
#define EVENT_HPP

#include <stdint.h>
#include <string>
#include <mosquittopp.h>

using namespace std;

#ifndef mosquitto_message_t
typedef struct mosquitto_message mqtt_message_t;
#endif


/**
 * Where did the event originate?
 */
namespace EventSource
{
    typedef enum
    {
        BLE,
        SPLITTER,
        MQTT
    } type;
}


/**
 * A struct containing all
 * relevant info about an event
 */
typedef struct
{
    /** The context in which this event was created */
    EventSource::type source;

    // If the event was generated by reading a BLE beacon:
    uint16_t shortUUIDService;
    uint16_t shortUUIDCharacteristic;
    char bleData[255];
    uint8_t bleDataLength;

    // If the event was generated after BLE data evaluation
    // and a checkerboard ID was determined using the config file:
    string checkerboardId;
    uint16_t sensorValue;

    // If the event was generated by an MQTT subscriber:
    mqtt_message_t* mqttMessage;
} event_t;


#endif
